accum-grad: 1
adim: 384
aheads: 4
batch-bins: 500000
batch-sort-key: output
bce-pos-weight: 10.0
decoder-concat-after: false
decoder-normalize-before: false
dlayers: 6
dprenet-dropout-rate: 0.5
dprenet-layers: 2
dprenet-units: 256
dunits: 1536
elayers: 6
embed-dim: 0
encoder-concat-after: false
encoder-normalize-before: false
epochs: 500
eprenet-conv-chans: 0
eprenet-conv-filts: 0
eprenet-conv-layers: 0
eprenet-dropout-rate: 0.0
eunits: 1536
grad-clip: 1.0
initial-decoder-alpha: 1.0
initial-encoder-alpha: 1.0
model-module: espnet.nets.pytorch_backend.e2e_tts_transformer:Transformer
opt: noam
patience: 0
postnet-chans: 256
postnet-dropout-rate: 0.5
postnet-filts: 5
postnet-layers: 5
pretrained-model: downloads/csmsc_mailabs/exp/train_pytorch_baseline/results/snapshot.ep.100
reduction-factor: 2
report-interval-iters: 10
save-interval-epoch: 50
spk-embed-integration-type: add
train-embedding: false
transformer-dec-attn-dropout-rate: 0.1
transformer-dec-dropout-rate: 0.1
transformer-dec-positional-dropout-rate: 0.1
transformer-enc-attn-dropout-rate: 0.1
transformer-enc-dec-attn-dropout-rate: 0.1
transformer-enc-dropout-rate: 0.1
transformer-enc-positional-dropout-rate: 0.1
transformer-init: pytorch
transformer-lr: 1.0
transformer-warmup-steps: 4000
use-batch-norm: true
use-guided-attn-loss: false
use-masking: true
use-scaled-pos-enc: true
use-speaker-embedding: true
weight-decay: 0.0
