aconv-chans: 32
aconv-filts: 15
adim: 128
atype: location
batch-size: 16
batch-sort-key: output
bce-pos-weight: 1.0
cumulate-att-w: true
dlayers: 2
dropout-rate: 0.5
dunits: 1024
econv-chans: 512
econv-filts: 5
econv-layers: 3
elayers: 1
embed-dim: 512
epochs: 1000
eps: 1e-6
eunits: 512
lr: 1e-3
patience: 0
postnet-chans: 512
postnet-filts: 5
postnet-layers: 5
prenet-layers: 2
prenet-units: 256
pretrained-model: downloads/csmsc_mailabs_taco2/exp/train_pytorch_train_pytorch_tacotron2+spkemb/results/model.loss.best
reduction-factor: 2
save-interval-epochs: 50
train-embedding: false
use-batch-norm: true
use-concate: true
use-guided-attn-loss: true
use-masking: true
use-residual: false
use-speaker-embedding: true
weight-decay: 0.0
zoneout-rate: 0.1
